<Project Sdk="Microsoft.NET.Sdk.Web">

	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
		<Nullable>enable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>
		<AllowUnsafeBlocks>True</AllowUnsafeBlocks>
		<NuGetAudit>false</NuGetAudit>
	</PropertyGroup>

	<ItemGroup>
	  <Compile Remove="ModelWeights\**" />
	  <Content Remove="ModelWeights\**" />
	  <EmbeddedResource Remove="ModelWeights\**" />
	  <None Remove="ModelWeights\**" />
	</ItemGroup>

  <ItemGroup>
    <PackageReference Include="BCrypt.Net-Next" Version="4.1.0" />
    <PackageReference Include="DotNetEnv" Version="3.1.1" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="10.0.5" />
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.4" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="10.0.5" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="10.0.5">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.ML.OnnxRuntime" Version="1.24.3" />
	<PackageReference Include="OpenCvSharp4" Version="4.10.0.20240717" />
	<PackageReference Include="OpenCvSharp4.runtime.win" Version="4.10.0.20240717" Condition="'$(OS)' == 'Windows_NT'" />
	<PackageReference Include="OpenCvSharp4.official.runtime.linux-x64.slim" Version="4.13.0.20260526" Condition="'$(OS)' != 'Windows_NT'" />
    <PackageReference Include="Serilog.AspNetCore" Version="10.0.0" />
    <PackageReference Include="Serilog.Sinks.Console" Version="6.1.1" />
    <PackageReference Include="Serilog.Sinks.File" Version="7.0.0" />
    <PackageReference Include="SixLabors.ImageSharp" Version="3.1.12" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="10.1.5" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Router\" />
    <Folder Include="PatchCore\Encoder\" />
    <Folder Include="PatchCore\Banks\" />
    <Folder Include="PatchCore\Metadata\" />
  </ItemGroup>

</Project>
